config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  get  "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  root "welcome#index"

end

app/models/question.rb
class Question < ActiveRecord::Base

  # when using 'has_many' you must put a symbol for the associated record in plural format
  # you also should provide the :dependent option which can be either:
  # :destroy: which deletes all the associated answers when the question is deleted
  # :nullify: which makes 'question_id' NULL for all associated answers
  has_many :answers, dependent: :destroy
  belongs_to :category
  belongs_to :user

  has_many :likes, dependent: :destroy
  # has_many :users, through: :likes
  has_many :liking_users, through: :likes, source: :user

  has_many :votes, dependent: :destroy
  has_many :voting_users, through: :votes, source: :user

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # validates_presence_of :title # deprecated
  # validates :title, :body, presence: true
  validates(:title, {presence: true, uniqueness: {message: "must be unique!"}})

  validates :body, length: {minimum: 5}

  validates :view_count, numericality: {greater_than_or_equal_to: 0}

  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  # validates :email, format: VALID_EMAIL_REGEX

  # this validates that the combination of title and body must be unique
  # it means that title by itself doesn't have to be unique and body by itself
  # doesn't have to be unique but the combination of the two must be unique

  # validates :title, uniqueness: {scope::body}
  # we use 'validate' to reference a method that will be used for our custom validation

  validate :no_monkey

  # this will call the 'set_defaults' method right after the initialize phase
  after_initialize :set_defaults

  before_validation :titleize_title

  extend FriendlyId
  friendly_id :title, use: :history

  # scope :recent_three, lambda { order("created_at DESC").limit(3) }2
  def self.recent_three
    order("created_at DESC").limit(3)
  end

  def self.search(search_term)
    # where(["title ILIKE :term OR body ILIKE :term", {term: "%#{search_term}%"}])
    where(["title ILIKE ? Or body ILIKE ?", "%#{search_term}%", "%#{search_term}%"])

  end

  def user_full_name
    user ? user.full_name : ""
  end

  def like_for(user)
    likes.find_by_user_id user if user
  end

  def vote_for(user)
    votes.find_by_user_id user if user
  end

  def vote_value
    votes.up_count - votes.down_count
  end

  # def to_param
  #   "#{id}-#{title}".parameterize
  # end

  private

  def titleize_title
    self.title = title.titleize
  end

  def set_defaults
    self.view_count ||= 0
  end

  def no_monkey
    if title.present? && title.downcase.include?("monkey")
      errors.add(:title, "No monkeys!")
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # Defining a method in as a 'before_action' will make it so that Rails executes that method before executing the action. This is still within the same request cycle.
  # You can give the 'before_action' method two options: :only or :except,
  # this will help you limit the actions which the 'find_questiion' method will be exectued before.
  # In the code below, 'find_question' will only be executed before: show, edit, update and destroy actions.
  # before_action(:find_question, {only: [:show, :update, :destroy]})

  before_action :find_question, only: [:edit, :update, :destroy, :show]
  before_action :authorize_question, only: [:edit, :update, :destroy]

  # include QuestionsAnswersHelper
  # helper_method :user_like

  def new
    # We need to define a new 'Question' object in order to properly generate a form in Rails
    # Question is the ActiveRecord model
    @question = Question.new
  end

  def create
    # Method 1
    # @question = Question.new
    # @question.title = params[:question][:title]
    # @question.body  = params[:question][:body]
    # @question.save!

    # Method 2
    # @question = Question.create({title: params[:question][:title],
                        # body:  params[:question][:body]})

    # Method 3
    # params[:question] looks like: {"title"=>"question from web", "body"=>"question body from web"}
    # @question = Question.create(params[:question])
    # this will throw a: ActiveModel::ForbiddenAttributesError exception

    # Method 4
    # We use Strong Parameters feature of Rails
    @question       = Question.new(question_params)
    @question.user  = current_user

    if @question.save
      flash[:notice] = "Question created!"
      # render :show
      # redirect_to question_path({id: @question.id})
      redirect_to question_path(@question)
    else
      flash[:alert] = "Question didn't save!"
      # this will render 'app/views/questions/new.html.erb' because the default in this action is to render 'app/views/question/create.html.erb'
      render :new
    end
  end

  # we receive a request such as : GET /questions/56
  # params[:id] will be '56'
  def show
    @answer = Answer.new
    respond_to do |format|
      format.html { render } # render questions/show.html.erb
      format.json { render json: @question.to_json }
      format.xml  { render xml: @question.to_xml }
    end
  end

  def index
    @questions = Question.all
    respond_to do |format|
      format.html { render }
      format.json { render json: @questions.select(:id, :title, :view_count) }
    end
  end

  def edit
  end

  def update
    @question.slug = nil
    if @question.update question_params
      # flash messages can be set either directly using: flash[:notice] = ".."
      # you can also pass a ':notice' or ':alert' options to the 'redirect_to' method
      redirect_to question_path(@question), notice: "Question updated!"
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: "Question: #{@question.title} deleted!"
  end

  private

  def authorize_question
    redirect_to root_path unless can? :crud, @question
  end

  def find_question
    @question = Question.friendly.find params[:id]
  end

  def question_params
    params.require(:question).permit([:title, :body, :category_id,
                                      {tag_ids: []}])
  end

  # def user_like
  #   @user_like ||= @question.like_for(current_user)
  # end
  # helper_method :user_like

end

app/helpers/questions_helper.rb
module QuestionsHelper

  def user_like
    @user_like ||= @question.like_for(current_user)
  end

end

app/views/questions/_form.html.erb
<%# form_for is a Rails helper method that accepts an ActiveRecord object as
    the first argument.
    if @question is not persisted in the database, form_for makes the `action`
    of the form go to `questions_path` (Rails convention) and it will make the
    `method` of `form` be POST
    %>

<%# this file '_form.html.erb' is considered to be a partial which means you can included it in any other template (such as new.html.erb and edit.html.erb). You must start the partial name with '_'. Partials have access to the same instance variables available in the templates (eg. @question)  %>

<%= @question.errors.full_messages.join(", ") %>
<%# If you give the `form_for` helper an ActiveRecord object that is persisted
    then the generated form will have an action that submits to
     `question_path(@question)` wherer @question is the ActiveRecord object that
     you passed to the form. The action will be PATCH (using the _method wordaround) %>

    <!-- using 'simple_form': -->
     <%= simple_form_for @question do |f| %>
       <%= f.input :title, input_html: {class: "abc"}, label_html: {class: "hey"} %>
       <%= f.input :body %>
       <%= f.association :category %>
       <%= f.association :tags, input_html: {class: "chosen-select"} %>
       <%= f.submit class: "btn btn-primary" %>
     <% end %>

<!-- <%= simple_form_for @question do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name %>
  </div>
  <div>
    <%= f.label :tag_ids, "Tags" %>
    <%= f.collection_check_boxes :tag_ids, Tag.order(:name), :id, :name %>
  </div>
  <%= f.submit class: "btn btn-primary"%>
<% end %> -->

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%# you can use full path `/questions/form` %>
<%#= render "/questions/form" %>

<%# if the partial is in the same folder, you can simply use: %>
<%= render "form" %>

<!--
<%= @question.errors.full_messages.join(", ") %>

<%# If you give the 'form_for' helper an ActiveRecord object that is persisted
    then the generated form will have an action that submits to 'question_path(@question)' where @question is the ActiveRecord object that you passed to the form. The action will be PATCH (using the _method workaround) %>

<%= form_for @question do |f| %>

  <div>
    <%= f.label :title %>
    <%# by using the f.text.field :title, if @question has a value for the attribute 'title' it will populate the field with that value. This is usually the case when redisplaying the form after an error occurs %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit %>

<% end %> -->

<%# you can use full path '/questions/form' %>
<%# render "questions" %>

app/views/questions/index.html.erb
<h1>All Questions</h1>

<% @questions.each do |q| %>
  <div>
    <%= link_to q.title, question_path(q) %>
  </div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

<!--
<%= @question.errors.full_messages.join(", ") %>

<%# form_for is a Rails helper method that accepts an ActiveRecord object as the first argument.
if @question is not persisted in the database, form_for makes the action of the form go to 'questions_path' (Rails convention) and it will make the 'method' of 'form' be POST.
%>

<%= form_for @question do |f| %>

  <div>
    <%= f.label :title %>
    <%# by using the f.text.field :title, if @question has a value for the attribute 'title' it will populate the field with that value. This is usually the case when redisplaying the form after an error occurs %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_field :body %>
  </div>
  <%= f.submit %>

<% end %> -->

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p>View Count: <%= @question.view_count %></p>
<p>Created By: <%= @question.user_full_name.titleize %></p>
<!-- <p>Tags: <%#= @question.tags.map(&:name).join(", ") %></p> -->
<p>Tags: <%= @question.tags.map{|t| t.name }.join(", ") %></p>
<%# can? is a helper method that came from the CanCanCan gem to help us enforce authorization rules in the views and controllers. We didn't specifically put rules for :edit and :destroy but we put a rule for :crud which includes both of them. %>
<% if can? :update, @question %>
  <%= link_to "Edit", edit_question_path(@question) %>
<% end %>
<% if can? :destroy, @question %>
  <%= link_to "Delete", question_path(@question),
                        method: :delete,
                        data: {confirm: "Are you sure?"} %>
<% end %>

<div id="question-like">
<%= render "/likes/like" %>
</div>

  <% user_vote = @question.vote_for(current_user) %>
  <% if user_vote && user_vote.is_up? %>
    <%= link_to "Undo Vote Up", question_vote_path(@question,    user_vote), method: :delete %>
    <%= link_to "Vote Down", question_vote_path(@question, user_vote, {vote: {is_up: false}}), method: :patch %>
  <% elsif user_vote %>
    <%= link_to "Vote Up", question_vote_path(@question, user_vote, {vote: {is_up: true}}), method: :patch %>
    <%= link_to "Undo Vote Down", question_vote_path(@question,    user_vote), method: :delete %>
  <% else %>
  <%= link_to "Vote Up", question_votes_path(@question, {vote: {is_up: true}}), method: :post %>
  <%= link_to "Vote Down", question_votes_path(@question, {vote: {is_up: false}}), method: :post %>
  <%#= @question.down_vote.count %>
  <% end %>
  (<%= @question.vote_value %>)
<hr>

<div id="answer-form">
  <%= render "/answers/form", answer: @answer %>
</div>

<h2>Answers</h2>
<div id="answers">
<% @question.answers.each do |ans| %>
  <%= render "/answers/answer", answer: ans %>
<% end %>
</div>

<!-- Modal -->
<div class="modal fade" id="edit-answer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Edit Answer</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>