config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  get  "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  root "welcome#index"

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email params[:email]
    if user
      user.generate_password_reset_data
      PasswordResetsMailer.send_instructions(user).deliver_later
    end
  end

  def edit
    @user = User.find_by_password_reset_token! params[:id]
  end

  def update
    @user = User.find_by_password_reset_token! params[:id]
    user_params = params.require(:user).permit(:password, :password_confirmation)
    if @user.password_reset_expired?
      redirect_to new_password_reset_path, alert: "Password reset expired. Try again."
    elsif @user.update user_params
      sign_in(@user)
      redirect_to root_path, notice: "Password was reset successfully!"
    else
      render :edit
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/create.html.erb
<h1>Your password reset instructions have been mailed to you</p>

app/views/password_resets/edit.html.erb
<h1>Enter a new password</h1>
<%= @user.errors.full_messages.join(", ") %>
<%= form_for @user, url: password_resets_path(@user.password_resets_token) do |f| %>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Reset Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>

<%= form_tag password_resets_path do %>
  <div>
    <%= label_tag :email %>
    <%= email_field_tag :email %>
  </div>
  <%= submit_tag "Email me Reset Instructions" %>
<% end %>