config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  get  "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  root "welcome#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  # by having this 'belongs_to' in the model we can easily fetch the question for a given answer by running:
  # answ = Answer.find(14)
  # q    = ans.question
  # belongs_to assumes that the 'answers' table has a foreign_key called question_id (Rails convention)
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  def user_full_name
    user ? user.full_name : ""
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question
  before_action :find_and_authorize_answer, only: :destroy

  # include QuestionsAnswersHelper
  # helper_method :user_like

  def create
    answer_params     = params.require(:answer).permit(:body)
    @answer           = Answer.new answer_params
    @answer.question  = @question
    @answer.user      = current_user
    respond_to do |format|
    if @answer.save
      AnswersMailer.notify_question_owner(@answer).deliver_later
      format.html { redirect_to question_path(@question), notice: "Thanks for answering" }
      format.js { render :create_success }
    else
      flash[:alert] = "Not saved!"
      # this will render the show.html.erb inside views/questions
      format.html { render "/questions/show" }
      format.js { render :create_failure }
    end
  end
end

  def destroy
    # redirect_to root_path unless can? :destroy, answer
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_path(@question), notice: "Answer deleted!" }
      format.js { render }
    end
  end

  def edit
    @answer = Answer.find params[:id]
  end

  def update
    if @answer.update answer_params
      redirect_to question_path(@question), notice: "Answer updated!"
    else
      render :edit
    end
  end

  private

  def find_question
    @question = Question.friendly.find params[:question_id]
  end

  def find_and_authorize_answer
    @answer = @question.answers.find params[:id]
    # head will stop the HTTP request and send a response code depending on the symbol (first argument) that you pass in.
    # head :unauthorized unless can? :destroy, @answer
    redirect_to root_path unless can? :destroy, @answer
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.erb
<%# dom_id is used to generate a unique HTML id for elements from an ActiveRecord object. It uses the object type and its id to generate a unique id. %>
<div id="<%= dom_id(answer) %>" style="<%= style if defined?(style) %>">
  <%= answer.body %><br><br>
  by: <%= answer.user_full_name.titleize %>
  <% if can? :destroy, answer %>
    <%= link_to "delete", question_answer_path(@question, answer),
                        data: {confirm: "Are you sure"},
                        method: :delete,
                        remote: true %>
  <% end %>
  <% if can? :edit, answer %>
  <%= link_to "Edit", edit_question_answer_path(@question, answer),
                      remote: true,
                      data: {toggle: "modal", target: "#edit-answer"},
                      class: "btn btn-primary btn-sm"
                      %>
    <!-- Button trigger modal -->
  <% end %>
  <hr>
</div>

app/views/answers/_form.html.erb
<%= @answer.errors.full_messages.join(", ") %>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%# adding a remote: true option to the form makes it so that the form submits with AJAX (prevent the default as well) %>

<!-- SIMPLE_FORM: -->
<%= simple_form_for [@question, answer], remote: true do |f| %>
  <%= f.input :body, label: false %>
  <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
<% end %>

<!-- <%= form_for [@question, answer], remote: true do |f| %>
  <%= f.text_area :body %>
  <%= f.submit data: {disable_with: "submitting..."}%>
<% end %> -->

app/views/answers/_modal_form.html.erb
<%= @answer.errors.full_messages.join(", ") %>
<%#= form_for @answer, url: question_answers_path(@question) do |f| %>
<%# adding a remote: true option to the form makes it so that the form submits with AJAX (prevent the default as well) %>
<%= form_for [@question, @answer], remote: true do |f| %>

<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel">Edit Answer</h4>
    </div>
    <div class="modal-body">
      <%= f.text_area :body %>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<% end %>

app/views/answers/create_failure.js.erb
$("#answer-form").html("<%= j render '/answers/form', answer: @answer %>");

app/views/answers/create_success.js.erb
$("#answers").prepend("<%= j render '/answers/answer', answer: @answer, style: 'display: none' %>");
$("#answer-form").html("<%= j render '/answers/form', answer: Answer.new %>");
$("#<%= dom_id(@answer) %>").slideDown(500);

app/views/answers/destroy.js.erb
$("#<%= dom_id(@answer) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/answers/edit.js.erb
$("#edit-answer").html("<%= j render 'modal_form' %>");