config/routes.rb
Rails.application.routes.draw do

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]

resources :password_resets, only: [:new, :create, :edit, :update]

  get "/home" => "welcome#index"

  get "/about" => "welcome#about", as: :about_us

  get  "/contact_us" => "contact_us#new"
  post "/contact_us" => "contact_us#create"

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  resources :questions do

    resources :answers, only: [:create, :destroy, :edit, :update]

    resources :likes, only: [:create, :destroy]

    resources :votes, only: [:create, :update, :destroy]
  end

  root "welcome#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <!-- <a href="<%= home_path %>">Home</a> -->
    <!-- link_to is a helper method that comes from Rails which generates an <a> HTML element. The 'link_to' method takes two primary arguments. The first argument is for the anchor text and the second argument is for the 'href' value (where you want to link to) %)  -->
    <%= link_to("Home", home_path, {class: "abc"}) %>
    <!-- <a href="<%= about_us_path %>">About</a> -->
    |
    <%= link_to "About", about_us_path({a: 'hello', b: 123}) %>
    |
    <%= link_to "Questions", questions_path %>
    |
    <%= link_to "Contact Us", contact_us_path %>
    |
    <%= link_to "New Question", new_question_path %>
    |
    <% if user_signed_in? %>
    Hello <%= current_user.first_name %>!
    <%= link_to "Log out", sessions_path, method: :delete %>
    <% else %>
    <%= link_to "Sign In", new_session_path %>
    <%= link_to "Sign Up", new_user_path %>
    <% end %>
    <!-- <%= flash[:notice] || flash[:alert] %> -->
    <%= notice || alert %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/special.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Awesome Answers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <a href="<%= home_path %>">Home</a> -->
  <%# link_to is a helper method that comes from Rails which generates an <a>
      HTML element. The `link_to` method takes two primary arguments. The first
      argument is for the anchor text and the second argument is for the `href`
      value (where you want to link to) %>
  <%= link_to("Home", home_path, {class: "abc"}) %>
  |
  <!-- <a href="<%= about_us_path %>">About</a> -->
  <%= link_to "About", about_us_path({a: 'hello', b: 123}) %>
  |
  <%= link_to "Contact Us", contact_us_path %>

  <hr>
  <h1>Special Layout</h1>
  <%= yield %>

</body>
</html>